# Generated by Django 5.2 on 2025-08-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
    ]
