# Generated by Django 5.2.3 on 2025-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('aceppted', 'Прийнято'), ('rejected', 'Відхилено')], default='new', max_length=10),
        ),
    ]
