# Generated by Django 5.2.3 on 2025-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_car_photo_alter_resume_status_alter_resume_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('user', 'Користувач')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images/'),
        ),
    ]
